local_costmap:
   global_frame: odom
   robot_base_frame: /base_footprint
   update_frequency: 15.0
   publish_frequency: 10
   static_map: false.0
   rolling_window: true
   width: 7.0
   height: 7.0
   resolution: 0.05
   transform_tolerance: 0.5
   plugins:
    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
